#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET")]
public partial class _linQ_Processa_DRE_SGC : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_Processa_DRE_SGC() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_Processa_DRE_SGC(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_Processa_DRE_SGC(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_Processa_DRE_SGC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_Processa_DRE_SGC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[Function(Name="dbo.Stp_Exec_DRE")]
	public int Stp_Exec_DRE([Parameter(Name="Mes", DbType="Int")] System.Nullable<int> mes, [Parameter(Name="Ano", DbType="Int")] System.Nullable<int> ano, [Parameter(Name="Tipo", DbType="VarChar(50)")] string tipo, [Parameter(Name="Login", DbType="VarChar(50)")] string login, [Parameter(Name="IP", DbType="VarChar(50)")] string iP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mes, ano, tipo, login, iP);
		return ((int)(result.ReturnValue));
	}
}
#pragma warning restore 1591
