#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V1")]
public partial class _linQ_ForFatDetalhesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_ForFatDetalhesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ForFatDetalhesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ForFatDetalhesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ForFatDetalhesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ForFatDetalhesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_FatDetalhes_Delete")]
	public int stp_FatDetalhes_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_FatDetalhes_Insert")]
	public int Stp_FatDetalhes_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Detalhes", DbType="Text")] string detalhes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoFat", DbType="VarChar(50)")] string tipoFat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="Money")] System.Nullable<decimal> valor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="Int")] System.Nullable<int> mes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(250)")] string userName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contratoID, detalhes, tipoFat, valor, mes, ano, userName);
		return ((int)(result.ReturnValue));
	}
}
#pragma warning restore 1591
