#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V1")]
public partial class _linQ_ContratosHST : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertContrato_History_Negociacoe(Contrato_History_Negociacoe instance);
  partial void UpdateContrato_History_Negociacoe(Contrato_History_Negociacoe instance);
  partial void DeleteContrato_History_Negociacoe(Contrato_History_Negociacoe instance);
  #endregion
	
	public _linQ_ContratosHST() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ContratosHST(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ContratosHST(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ContratosHST(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ContratosHST(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Contrato_History_Negociacoe> Contrato_History_Negociacoes
	{
		get
		{
			return this.GetTable<Contrato_History_Negociacoe>();
		}
	}
	
	public System.Data.Linq.Table<Contrato1> Contrato1s
	{
		get
		{
			return this.GetTable<Contrato1>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_Contrato_History_Negociacoes_Update")]
	public int stp_Contrato_History_Negociacoes_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pleito", DbType="VarChar(300)")] string pleito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DataAbertura", DbType="VarChar(50)")] string dataAbertura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnoBase", DbType="VarChar(50)")] string anoBase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrevisaoConclusao", DbType="VarChar(50)")] string previsaoConclusao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(150)")] string valor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Impacto", DbType="VarChar(100)")] string impacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Responsaveis", DbType="Text")] string responsaveis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(100)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observacoes", DbType="Text")] string observacoes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(200)")] string fullName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, pleito, dataAbertura, anoBase, previsaoConclusao, valor, tipo, impacto, responsaveis, status, observacoes, fullName);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_Contrato_History_Negociacoes_Insert")]
	public int stp_Contrato_History_Negociacoes_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pleito", DbType="VarChar(300)")] string pleito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DataAbertura", DbType="VarChar(50)")] string dataAbertura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnoBase", DbType="VarChar(50)")] string anoBase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrevisaoConclusao", DbType="VarChar(50)")] string previsaoConclusao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(150)")] string valor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Impacto", DbType="VarChar(100)")] string impacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Responsaveis", DbType="Text")] string responsaveis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(100)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observacoes", DbType="Text")] string observacoes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(200)")] string fullName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contratoID, pleito, dataAbertura, anoBase, previsaoConclusao, valor, tipo, impacto, responsaveis, status, observacoes, fullName);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_Contrato_History_Negociacoes_Anexo_insert")]
	public int stp_Contrato_History_Negociacoes_Anexo_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HST_ID", DbType="Int")] System.Nullable<int> hST_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomeArquivo", DbType="VarChar(300)")] string nomeArquivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Extensao", DbType="VarChar(6)")] string extensao)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hST_ID, nomeArquivo, extensao);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contrato_History_Negociacoes")]
public partial class Contrato_History_Negociacoe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ContratoID;
	
	private string _Pleito;
	
	private string _DataAbertura;
	
	private string _AnoBase;
	
	private string _PrevisaoConclusao;
	
	private string _Valor;
	
	private string _Tipo;
	
	private string _Impacto;
	
	private string _Responsaveis;
	
	private string _Status;
	
	private string _Observacoes;
	
	private string _Editor;
	
	private System.Nullable<System.DateTime> _DataCadastro;
	
	private System.Nullable<System.DateTime> _UltimaAtualizacao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnContratoIDChanging(System.Nullable<int> value);
    partial void OnContratoIDChanged();
    partial void OnPleitoChanging(string value);
    partial void OnPleitoChanged();
    partial void OnDataAberturaChanging(string value);
    partial void OnDataAberturaChanged();
    partial void OnAnoBaseChanging(string value);
    partial void OnAnoBaseChanged();
    partial void OnPrevisaoConclusaoChanging(string value);
    partial void OnPrevisaoConclusaoChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnImpactoChanging(string value);
    partial void OnImpactoChanged();
    partial void OnResponsaveisChanging(string value);
    partial void OnResponsaveisChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnObservacoesChanging(string value);
    partial void OnObservacoesChanged();
    partial void OnEditorChanging(string value);
    partial void OnEditorChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    partial void OnUltimaAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnUltimaAtualizacaoChanged();
    #endregion
	
	public Contrato_History_Negociacoe()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContratoID", DbType="Int")]
	public System.Nullable<int> ContratoID
	{
		get
		{
			return this._ContratoID;
		}
		set
		{
			if ((this._ContratoID != value))
			{
				this.OnContratoIDChanging(value);
				this.SendPropertyChanging();
				this._ContratoID = value;
				this.SendPropertyChanged("ContratoID");
				this.OnContratoIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pleito", DbType="VarChar(300)")]
	public string Pleito
	{
		get
		{
			return this._Pleito;
		}
		set
		{
			if ((this._Pleito != value))
			{
				this.OnPleitoChanging(value);
				this.SendPropertyChanging();
				this._Pleito = value;
				this.SendPropertyChanged("Pleito");
				this.OnPleitoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAbertura", DbType="VarChar(50)")]
	public string DataAbertura
	{
		get
		{
			return this._DataAbertura;
		}
		set
		{
			if ((this._DataAbertura != value))
			{
				this.OnDataAberturaChanging(value);
				this.SendPropertyChanging();
				this._DataAbertura = value;
				this.SendPropertyChanged("DataAbertura");
				this.OnDataAberturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnoBase", DbType="VarChar(50)")]
	public string AnoBase
	{
		get
		{
			return this._AnoBase;
		}
		set
		{
			if ((this._AnoBase != value))
			{
				this.OnAnoBaseChanging(value);
				this.SendPropertyChanging();
				this._AnoBase = value;
				this.SendPropertyChanged("AnoBase");
				this.OnAnoBaseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrevisaoConclusao", DbType="VarChar(50)")]
	public string PrevisaoConclusao
	{
		get
		{
			return this._PrevisaoConclusao;
		}
		set
		{
			if ((this._PrevisaoConclusao != value))
			{
				this.OnPrevisaoConclusaoChanging(value);
				this.SendPropertyChanging();
				this._PrevisaoConclusao = value;
				this.SendPropertyChanged("PrevisaoConclusao");
				this.OnPrevisaoConclusaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="VarChar(50)")]
	public string Valor
	{
		get
		{
			return this._Valor;
		}
		set
		{
			if ((this._Valor != value))
			{
				this.OnValorChanging(value);
				this.SendPropertyChanging();
				this._Valor = value;
				this.SendPropertyChanged("Valor");
				this.OnValorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Tipo
	{
		get
		{
			return this._Tipo;
		}
		set
		{
			if ((this._Tipo != value))
			{
				this.OnTipoChanging(value);
				this.SendPropertyChanging();
				this._Tipo = value;
				this.SendPropertyChanged("Tipo");
				this.OnTipoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impacto", DbType="VarChar(100)")]
	public string Impacto
	{
		get
		{
			return this._Impacto;
		}
		set
		{
			if ((this._Impacto != value))
			{
				this.OnImpactoChanging(value);
				this.SendPropertyChanging();
				this._Impacto = value;
				this.SendPropertyChanged("Impacto");
				this.OnImpactoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsaveis", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Responsaveis
	{
		get
		{
			return this._Responsaveis;
		}
		set
		{
			if ((this._Responsaveis != value))
			{
				this.OnResponsaveisChanging(value);
				this.SendPropertyChanging();
				this._Responsaveis = value;
				this.SendPropertyChanged("Responsaveis");
				this.OnResponsaveisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(100)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacoes", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Observacoes
	{
		get
		{
			return this._Observacoes;
		}
		set
		{
			if ((this._Observacoes != value))
			{
				this.OnObservacoesChanging(value);
				this.SendPropertyChanging();
				this._Observacoes = value;
				this.SendPropertyChanged("Observacoes");
				this.OnObservacoesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editor", DbType="VarChar(200)")]
	public string Editor
	{
		get
		{
			return this._Editor;
		}
		set
		{
			if ((this._Editor != value))
			{
				this.OnEditorChanging(value);
				this.SendPropertyChanging();
				this._Editor = value;
				this.SendPropertyChanged("Editor");
				this.OnEditorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime")]
	public System.Nullable<System.DateTime> DataCadastro
	{
		get
		{
			return this._DataCadastro;
		}
		set
		{
			if ((this._DataCadastro != value))
			{
				this.OnDataCadastroChanging(value);
				this.SendPropertyChanging();
				this._DataCadastro = value;
				this.SendPropertyChanged("DataCadastro");
				this.OnDataCadastroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaAtualizacao", DbType="DateTime")]
	public System.Nullable<System.DateTime> UltimaAtualizacao
	{
		get
		{
			return this._UltimaAtualizacao;
		}
		set
		{
			if ((this._UltimaAtualizacao != value))
			{
				this.OnUltimaAtualizacaoChanging(value);
				this.SendPropertyChanging();
				this._UltimaAtualizacao = value;
				this.SendPropertyChanged("UltimaAtualizacao");
				this.OnUltimaAtualizacaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contrato")]
public partial class Contrato1
{
	
	private System.Nullable<int> _ContratoID;
	
	private string _BU;
	
	private string _DescContract;
	
	private System.Nullable<int> _NucleoID;
	
	private System.Nullable<int> _GrupoContractID;
	
	private System.Nullable<int> _Regional;
	
	private System.Nullable<int> _ProdutoPrincipal;
	
	private System.Nullable<int> _SeguimentoID;
	
	private System.Nullable<int> _TipoVenda;
	
	private System.Nullable<int> _RDNID;
	
	private System.Nullable<int> _RCNID;
	
	private System.Nullable<int> _Cod_PCP;
	
	private string _Razao_Social;
	
	private string _CNPJ;
	
	private string _IE;
	
	private string _Contato;
	
	private string _Telefone_Contato;
	
	private string _Email_Contato;
	
	private string _Endereco;
	
	private string _Numero;
	
	private string _Complemento;
	
	private string _Bairro;
	
	private string _Cidade;
	
	private string _UF;
	
	private string _Pais;
	
	private string _CEP;
	
	private System.Nullable<int> _SituacaoContratual;
	
	private System.Nullable<int> _Pendencia;
	
	private string _DescPendencia;
	
	private string _ResponsPendSitContrat;
	
	private string _CodDocContratual;
	
	private string _DataInicioAtividades;
	
	private string _DataAssinaturaContrato;
	
	private string _DataRescisao;
	
	private string _DataVencimentoContrato;
	
	private string _SituacaoArquivoCentral;
	
	private string _ObsSituacaoArqCentral;
	
	private System.Nullable<int> _Performance;
	
	private System.Nullable<decimal> _ValorMensal;
	
	private System.Nullable<decimal> _ISSQN;
	
	private System.Nullable<decimal> _PIS_COFINS;
	
	private System.Nullable<decimal> _ICMS;
	
	private System.Nullable<decimal> _IPI;
	
	private string _CondicaoPagamento;
	
	private string _DataProximoReajuste;
	
	private System.Nullable<int> _BaseReajuste;
	
	private string _ClausulaReajuste;
	
	private System.Nullable<int> _Filial;
	
	private string _SituacaoFilial;
	
	private string _EnderecoFilial;
	
	private string _PendenciaAberturaFilial;
	
	private string _ResponsavelAberturaFilial;
	
	private string _DataLimiteAberturaFilial;
	
	private System.Nullable<int> _AcompLibMes;
	
	private System.Nullable<int> _AcompLibAno;
	
	private System.Nullable<int> _AcompLibDia;
	
	private System.Nullable<int> _DataMMHistory;
	
	private System.Nullable<int> _DataAAHistory;
	
	public Contrato1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContratoID", DbType="Int")]
	public System.Nullable<int> ContratoID
	{
		get
		{
			return this._ContratoID;
		}
		set
		{
			if ((this._ContratoID != value))
			{
				this._ContratoID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50)")]
	public string BU
	{
		get
		{
			return this._BU;
		}
		set
		{
			if ((this._BU != value))
			{
				this._BU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescContract", DbType="VarChar(200)")]
	public string DescContract
	{
		get
		{
			return this._DescContract;
		}
		set
		{
			if ((this._DescContract != value))
			{
				this._DescContract = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NucleoID", DbType="Int")]
	public System.Nullable<int> NucleoID
	{
		get
		{
			return this._NucleoID;
		}
		set
		{
			if ((this._NucleoID != value))
			{
				this._NucleoID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoContractID", DbType="Int")]
	public System.Nullable<int> GrupoContractID
	{
		get
		{
			return this._GrupoContractID;
		}
		set
		{
			if ((this._GrupoContractID != value))
			{
				this._GrupoContractID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regional", DbType="Int")]
	public System.Nullable<int> Regional
	{
		get
		{
			return this._Regional;
		}
		set
		{
			if ((this._Regional != value))
			{
				this._Regional = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdutoPrincipal", DbType="Int")]
	public System.Nullable<int> ProdutoPrincipal
	{
		get
		{
			return this._ProdutoPrincipal;
		}
		set
		{
			if ((this._ProdutoPrincipal != value))
			{
				this._ProdutoPrincipal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeguimentoID", DbType="Int")]
	public System.Nullable<int> SeguimentoID
	{
		get
		{
			return this._SeguimentoID;
		}
		set
		{
			if ((this._SeguimentoID != value))
			{
				this._SeguimentoID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVenda", DbType="Int")]
	public System.Nullable<int> TipoVenda
	{
		get
		{
			return this._TipoVenda;
		}
		set
		{
			if ((this._TipoVenda != value))
			{
				this._TipoVenda = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDNID", DbType="Int")]
	public System.Nullable<int> RDNID
	{
		get
		{
			return this._RDNID;
		}
		set
		{
			if ((this._RDNID != value))
			{
				this._RDNID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCNID", DbType="Int")]
	public System.Nullable<int> RCNID
	{
		get
		{
			return this._RCNID;
		}
		set
		{
			if ((this._RCNID != value))
			{
				this._RCNID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_PCP", DbType="Int")]
	public System.Nullable<int> Cod_PCP
	{
		get
		{
			return this._Cod_PCP;
		}
		set
		{
			if ((this._Cod_PCP != value))
			{
				this._Cod_PCP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razao_Social", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Razao_Social
	{
		get
		{
			return this._Razao_Social;
		}
		set
		{
			if ((this._Razao_Social != value))
			{
				this._Razao_Social = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(50)")]
	public string CNPJ
	{
		get
		{
			return this._CNPJ;
		}
		set
		{
			if ((this._CNPJ != value))
			{
				this._CNPJ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE", DbType="VarChar(50)")]
	public string IE
	{
		get
		{
			return this._IE;
		}
		set
		{
			if ((this._IE != value))
			{
				this._IE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contato", DbType="VarChar(50)")]
	public string Contato
	{
		get
		{
			return this._Contato;
		}
		set
		{
			if ((this._Contato != value))
			{
				this._Contato = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone_Contato", DbType="VarChar(20)")]
	public string Telefone_Contato
	{
		get
		{
			return this._Telefone_Contato;
		}
		set
		{
			if ((this._Telefone_Contato != value))
			{
				this._Telefone_Contato = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Contato", DbType="VarChar(50)")]
	public string Email_Contato
	{
		get
		{
			return this._Email_Contato;
		}
		set
		{
			if ((this._Email_Contato != value))
			{
				this._Email_Contato = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(150)")]
	public string Endereco
	{
		get
		{
			return this._Endereco;
		}
		set
		{
			if ((this._Endereco != value))
			{
				this._Endereco = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(10)")]
	public string Numero
	{
		get
		{
			return this._Numero;
		}
		set
		{
			if ((this._Numero != value))
			{
				this._Numero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(60)")]
	public string Complemento
	{
		get
		{
			return this._Complemento;
		}
		set
		{
			if ((this._Complemento != value))
			{
				this._Complemento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50)")]
	public string Bairro
	{
		get
		{
			return this._Bairro;
		}
		set
		{
			if ((this._Bairro != value))
			{
				this._Bairro = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
	public string Cidade
	{
		get
		{
			return this._Cidade;
		}
		set
		{
			if ((this._Cidade != value))
			{
				this._Cidade = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
	public string UF
	{
		get
		{
			return this._UF;
		}
		set
		{
			if ((this._UF != value))
			{
				this._UF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50)")]
	public string Pais
	{
		get
		{
			return this._Pais;
		}
		set
		{
			if ((this._Pais != value))
			{
				this._Pais = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(50)")]
	public string CEP
	{
		get
		{
			return this._CEP;
		}
		set
		{
			if ((this._CEP != value))
			{
				this._CEP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituacaoContratual", DbType="Int")]
	public System.Nullable<int> SituacaoContratual
	{
		get
		{
			return this._SituacaoContratual;
		}
		set
		{
			if ((this._SituacaoContratual != value))
			{
				this._SituacaoContratual = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendencia", DbType="Int")]
	public System.Nullable<int> Pendencia
	{
		get
		{
			return this._Pendencia;
		}
		set
		{
			if ((this._Pendencia != value))
			{
				this._Pendencia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescPendencia", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string DescPendencia
	{
		get
		{
			return this._DescPendencia;
		}
		set
		{
			if ((this._DescPendencia != value))
			{
				this._DescPendencia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsPendSitContrat", DbType="VarChar(50)")]
	public string ResponsPendSitContrat
	{
		get
		{
			return this._ResponsPendSitContrat;
		}
		set
		{
			if ((this._ResponsPendSitContrat != value))
			{
				this._ResponsPendSitContrat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDocContratual", DbType="VarChar(50)")]
	public string CodDocContratual
	{
		get
		{
			return this._CodDocContratual;
		}
		set
		{
			if ((this._CodDocContratual != value))
			{
				this._CodDocContratual = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInicioAtividades", DbType="VarChar(50)")]
	public string DataInicioAtividades
	{
		get
		{
			return this._DataInicioAtividades;
		}
		set
		{
			if ((this._DataInicioAtividades != value))
			{
				this._DataInicioAtividades = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAssinaturaContrato", DbType="VarChar(50)")]
	public string DataAssinaturaContrato
	{
		get
		{
			return this._DataAssinaturaContrato;
		}
		set
		{
			if ((this._DataAssinaturaContrato != value))
			{
				this._DataAssinaturaContrato = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRescisao", DbType="VarChar(50)")]
	public string DataRescisao
	{
		get
		{
			return this._DataRescisao;
		}
		set
		{
			if ((this._DataRescisao != value))
			{
				this._DataRescisao = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVencimentoContrato", DbType="VarChar(50)")]
	public string DataVencimentoContrato
	{
		get
		{
			return this._DataVencimentoContrato;
		}
		set
		{
			if ((this._DataVencimentoContrato != value))
			{
				this._DataVencimentoContrato = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituacaoArquivoCentral", DbType="VarChar(50)")]
	public string SituacaoArquivoCentral
	{
		get
		{
			return this._SituacaoArquivoCentral;
		}
		set
		{
			if ((this._SituacaoArquivoCentral != value))
			{
				this._SituacaoArquivoCentral = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObsSituacaoArqCentral", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string ObsSituacaoArqCentral
	{
		get
		{
			return this._ObsSituacaoArqCentral;
		}
		set
		{
			if ((this._ObsSituacaoArqCentral != value))
			{
				this._ObsSituacaoArqCentral = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Performance", DbType="Int")]
	public System.Nullable<int> Performance
	{
		get
		{
			return this._Performance;
		}
		set
		{
			if ((this._Performance != value))
			{
				this._Performance = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorMensal", DbType="Money")]
	public System.Nullable<decimal> ValorMensal
	{
		get
		{
			return this._ValorMensal;
		}
		set
		{
			if ((this._ValorMensal != value))
			{
				this._ValorMensal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSQN", DbType="Money")]
	public System.Nullable<decimal> ISSQN
	{
		get
		{
			return this._ISSQN;
		}
		set
		{
			if ((this._ISSQN != value))
			{
				this._ISSQN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIS_COFINS", DbType="Money")]
	public System.Nullable<decimal> PIS_COFINS
	{
		get
		{
			return this._PIS_COFINS;
		}
		set
		{
			if ((this._PIS_COFINS != value))
			{
				this._PIS_COFINS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICMS", DbType="Money")]
	public System.Nullable<decimal> ICMS
	{
		get
		{
			return this._ICMS;
		}
		set
		{
			if ((this._ICMS != value))
			{
				this._ICMS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPI", DbType="Money")]
	public System.Nullable<decimal> IPI
	{
		get
		{
			return this._IPI;
		}
		set
		{
			if ((this._IPI != value))
			{
				this._IPI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CondicaoPagamento", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string CondicaoPagamento
	{
		get
		{
			return this._CondicaoPagamento;
		}
		set
		{
			if ((this._CondicaoPagamento != value))
			{
				this._CondicaoPagamento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataProximoReajuste", DbType="VarChar(50)")]
	public string DataProximoReajuste
	{
		get
		{
			return this._DataProximoReajuste;
		}
		set
		{
			if ((this._DataProximoReajuste != value))
			{
				this._DataProximoReajuste = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseReajuste", DbType="Int")]
	public System.Nullable<int> BaseReajuste
	{
		get
		{
			return this._BaseReajuste;
		}
		set
		{
			if ((this._BaseReajuste != value))
			{
				this._BaseReajuste = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClausulaReajuste", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string ClausulaReajuste
	{
		get
		{
			return this._ClausulaReajuste;
		}
		set
		{
			if ((this._ClausulaReajuste != value))
			{
				this._ClausulaReajuste = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filial", DbType="Int")]
	public System.Nullable<int> Filial
	{
		get
		{
			return this._Filial;
		}
		set
		{
			if ((this._Filial != value))
			{
				this._Filial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituacaoFilial", DbType="VarChar(50)")]
	public string SituacaoFilial
	{
		get
		{
			return this._SituacaoFilial;
		}
		set
		{
			if ((this._SituacaoFilial != value))
			{
				this._SituacaoFilial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnderecoFilial", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string EnderecoFilial
	{
		get
		{
			return this._EnderecoFilial;
		}
		set
		{
			if ((this._EnderecoFilial != value))
			{
				this._EnderecoFilial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PendenciaAberturaFilial", DbType="VarChar(50)")]
	public string PendenciaAberturaFilial
	{
		get
		{
			return this._PendenciaAberturaFilial;
		}
		set
		{
			if ((this._PendenciaAberturaFilial != value))
			{
				this._PendenciaAberturaFilial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsavelAberturaFilial", DbType="VarChar(50)")]
	public string ResponsavelAberturaFilial
	{
		get
		{
			return this._ResponsavelAberturaFilial;
		}
		set
		{
			if ((this._ResponsavelAberturaFilial != value))
			{
				this._ResponsavelAberturaFilial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataLimiteAberturaFilial", DbType="VarChar(50)")]
	public string DataLimiteAberturaFilial
	{
		get
		{
			return this._DataLimiteAberturaFilial;
		}
		set
		{
			if ((this._DataLimiteAberturaFilial != value))
			{
				this._DataLimiteAberturaFilial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcompLibMes", DbType="Int")]
	public System.Nullable<int> AcompLibMes
	{
		get
		{
			return this._AcompLibMes;
		}
		set
		{
			if ((this._AcompLibMes != value))
			{
				this._AcompLibMes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcompLibAno", DbType="Int")]
	public System.Nullable<int> AcompLibAno
	{
		get
		{
			return this._AcompLibAno;
		}
		set
		{
			if ((this._AcompLibAno != value))
			{
				this._AcompLibAno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcompLibDia", DbType="Int")]
	public System.Nullable<int> AcompLibDia
	{
		get
		{
			return this._AcompLibDia;
		}
		set
		{
			if ((this._AcompLibDia != value))
			{
				this._AcompLibDia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataMMHistory", DbType="Int")]
	public System.Nullable<int> DataMMHistory
	{
		get
		{
			return this._DataMMHistory;
		}
		set
		{
			if ((this._DataMMHistory != value))
			{
				this._DataMMHistory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAAHistory", DbType="Int")]
	public System.Nullable<int> DataAAHistory
	{
		get
		{
			return this._DataAAHistory;
		}
		set
		{
			if ((this._DataAAHistory != value))
			{
				this._DataAAHistory = value;
			}
		}
	}
}
#pragma warning restore 1591
