#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V1")]
public partial class _linQ_CriaBuget_e_RagDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_CriaBuget_e_RagDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_CriaBuget_e_RagDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_CriaBuget_e_RagDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_CriaBuget_e_RagDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_CriaBuget_e_RagDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STP_CRIAR_BUDGET_RAG")]
	public int STP_CRIAR_BUDGET_RAG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RAG", DbType="Int")] System.Nullable<int> rAG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANO", DbType="Int")] System.Nullable<int> aNO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BU", DbType="VarChar(50)")] string bU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PA", DbType="VarChar(1)")] string pA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PercPA", DbType="Int")] System.Nullable<int> percPA)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rAG, aNO, bU, pA, percPA);
		return ((int)(result.ReturnValue));
	}
}
#pragma warning restore 1591
