#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V1")]
public partial class _linQ_InsertRollingDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_InsertRollingDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_InsertRollingDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_InsertRollingDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_InsertRollingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_InsertRollingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_Insert_Forecast_Rolling")]
	public int Stp_Insert_Forecast_Rolling([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContaID", DbType="Int")] System.Nullable<int> contaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoConta", DbType="Int")] System.Nullable<int> tipoConta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="Int")] System.Nullable<int> mes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="Money")] System.Nullable<decimal> valor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlagPub", DbType="VarChar(50)")] string flagPub, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dt_emissao_NF, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dt_venc_NF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BU", DbType="VarChar(50)")] string bU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="VarChar(50)")] string login)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contaID, contratoID, tipoConta, ano, mes, valor, flagPub, dt_emissao_NF, dt_venc_NF, bU, login);
		return ((int)(result.ReturnValue));
	}
}
#pragma warning restore 1591
