#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V2")]
public partial class linQ_rsk_stps : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public linQ_rsk_stps() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_stps(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_stps(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_stps(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_stps(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_rsk_delete_riscos_detalhes")]
	public int stp_rsk_delete_riscos_detalhes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_rsk_Mit_Insert")]
	public int Stp_rsk_Mit_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DetID", DbType="Int")] System.Nullable<int> detID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescFatorM", DbType="VarChar(50)")] string descFatorM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorFatorM", DbType="Money")] System.Nullable<decimal> valorFatorM)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), detID, descFatorM, valorFatorM);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_rsk_riscos_delete")]
	public int stp_rsk_riscos_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RiscoID", DbType="Int")] System.Nullable<int> riscoID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), riscoID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_tbl_riskManager_update")]
	public int Stp_tbl_riskManager_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoVenda", DbType="VarChar(50)")] string tipoVenda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescCN", DbType="VarChar(250)")] string descCN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SitContratual", DbType="VarChar(50)")] string sitContratual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RiscoInadimplencia", DbType="VarChar(50)")] string riscoInadimplencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CasoGreveComau", DbType="VarChar(50)")] string casoGreveComau, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CasoForcaMaior", DbType="VarChar(50)")] string casoForcaMaior, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DataVigencia", DbType="VarChar(10)")] string dataVigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefEconomico", DbType="VarChar(50)")] string refEconomico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseFat", DbType="VarChar(50)")] string baseFat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseFatValor", DbType="Money")] System.Nullable<decimal> baseFatValor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT_Baixa", DbType="Float")] System.Nullable<double> mT_Baixa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT_Alta", DbType="Float")] System.Nullable<double> mT_Alta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RiskID", DbType="Int")] System.Nullable<int> riskID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipoVenda, descCN, sitContratual, riscoInadimplencia, casoGreveComau, casoForcaMaior, dataVigencia, refEconomico, baseFat, baseFatValor, mT_Baixa, mT_Alta, riskID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_tbl_riskManager_insert")]
	public int Stp_tbl_riskManager_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoVenda", DbType="VarChar(50)")] string tipoVenda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescCN", DbType="VarChar(250)")] string descCN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SitContratual", DbType="VarChar(50)")] string sitContratual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RiscoInadimplencia", DbType="VarChar(50)")] string riscoInadimplencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CasoGreveComau", DbType="VarChar(50)")] string casoGreveComau, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CasoForcaMaior", DbType="VarChar(50)")] string casoForcaMaior, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DataVigencia", DbType="VarChar(10)")] string dataVigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefEconomico", DbType="VarChar(50)")] string refEconomico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseFat", DbType="VarChar(50)")] string baseFat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseFatValor", DbType="Money")] System.Nullable<decimal> baseFatValor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT_Baixa", DbType="Float")] System.Nullable<double> mT_Baixa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT_Alta", DbType="Float")] System.Nullable<double> mT_Alta)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipoVenda, descCN, sitContratual, riscoInadimplencia, casoGreveComau, casoForcaMaior, dataVigencia, refEconomico, baseFat, baseFatValor, mT_Baixa, mT_Alta);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_rsk_Max_Ids_tbls")]
	public int stp_rsk_Max_Ids_tbls([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod", DbType="Int")] System.Nullable<int> cod)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Stp_tbl_riskManager_Cad2_insert")]
	public int Stp_tbl_riskManager_Cad2_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RiskID", DbType="Int")] System.Nullable<int> riskID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Qualificacao", DbType="VarChar(150)")] string qualificacao, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desc", DbType="VarChar(200)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemContrato", DbType="VarChar(200)")] string itemContrato, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorImpactoRisco", DbType="Money")] System.Nullable<decimal> valorImpactoRisco, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OcorrenciaX", DbType="VarChar(50)")] string ocorrenciaX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImpactoY", DbType="VarChar(50)")] string impactoY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescFatorM", DbType="VarChar(50)")] string descFatorM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorFatorM", DbType="Money")] System.Nullable<decimal> valorFatorM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorImpactoReal", DbType="Money")] System.Nullable<decimal> valorImpactoReal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GrauRisco", DbType="Int")] System.Nullable<int> grauRisco, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> impactoXmetrica)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, riskID, qualificacao, desc, itemContrato, valorImpactoRisco, ocorrenciaX, impactoY, descFatorM, valorFatorM, valorImpactoReal, grauRisco, impactoXmetrica);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_rsk_sum_Forecast")]
	public int stp_rsk_sum_Forecast([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FatouMBC", DbType="VarChar(3)")] string fatouMBC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contratoID, fatouMBC, ano);
		return ((int)(result.ReturnValue));
	}
}
#pragma warning restore 1591
