#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET")]
public partial class _linQ_RateioSESMT : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_RateioSESMT() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_RateioSESMT(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_RateioSESMT(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_RateioSESMT(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_RateioSESMT(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Contrato_Recebe_Rateios_SESMT> Contrato_Recebe_Rateios_SESMTs
	{
		get
		{
			return this.GetTable<Contrato_Recebe_Rateios_SESMT>();
		}
	}
	
	[Function(Name="dbo.SP_Rateios_SESMT")]
	public int SP_Rateios_SESMT([Parameter(Name="Mes", DbType="Int")] System.Nullable<int> mes, [Parameter(Name="Ano", DbType="Int")] System.Nullable<int> ano, [Parameter(Name="Tipo", DbType="VarChar(50)")] string tipo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mes, ano, tipo);
		return ((int)(result.ReturnValue));
	}
}

[Table(Name="dbo.Contrato_Recebe_Rateios_SESMT")]
public partial class Contrato_Recebe_Rateios_SESMT
{
	
	private System.Nullable<int> _ContratoID;
	
	private System.Nullable<int> _ContaID;
	
	private System.Nullable<int> _TipoConta;
	
	private System.Nullable<decimal> _Valor;
	
	private System.Nullable<int> _ContratoID_Pai;
	
	private System.Nullable<int> _Mes;
	
	private System.Nullable<int> _Ano;
	
	private string _Tipo;
	
	private System.Nullable<char> _FlagPub;
	
	public Contrato_Recebe_Rateios_SESMT()
	{
	}
	
	[Column(Storage="_ContratoID", DbType="Int")]
	public System.Nullable<int> ContratoID
	{
		get
		{
			return this._ContratoID;
		}
		set
		{
			if ((this._ContratoID != value))
			{
				this._ContratoID = value;
			}
		}
	}
	
	[Column(Storage="_ContaID", DbType="Int")]
	public System.Nullable<int> ContaID
	{
		get
		{
			return this._ContaID;
		}
		set
		{
			if ((this._ContaID != value))
			{
				this._ContaID = value;
			}
		}
	}
	
	[Column(Storage="_TipoConta", DbType="Int")]
	public System.Nullable<int> TipoConta
	{
		get
		{
			return this._TipoConta;
		}
		set
		{
			if ((this._TipoConta != value))
			{
				this._TipoConta = value;
			}
		}
	}
	
	[Column(Storage="_Valor", DbType="Money")]
	public System.Nullable<decimal> Valor
	{
		get
		{
			return this._Valor;
		}
		set
		{
			if ((this._Valor != value))
			{
				this._Valor = value;
			}
		}
	}
	
	[Column(Storage="_ContratoID_Pai", DbType="Int")]
	public System.Nullable<int> ContratoID_Pai
	{
		get
		{
			return this._ContratoID_Pai;
		}
		set
		{
			if ((this._ContratoID_Pai != value))
			{
				this._ContratoID_Pai = value;
			}
		}
	}
	
	[Column(Storage="_Mes", DbType="Int")]
	public System.Nullable<int> Mes
	{
		get
		{
			return this._Mes;
		}
		set
		{
			if ((this._Mes != value))
			{
				this._Mes = value;
			}
		}
	}
	
	[Column(Storage="_Ano", DbType="Int")]
	public System.Nullable<int> Ano
	{
		get
		{
			return this._Ano;
		}
		set
		{
			if ((this._Ano != value))
			{
				this._Ano = value;
			}
		}
	}
	
	[Column(Storage="_Tipo", DbType="VarChar(50)")]
	public string Tipo
	{
		get
		{
			return this._Tipo;
		}
		set
		{
			if ((this._Tipo != value))
			{
				this._Tipo = value;
			}
		}
	}
	
	[Column(Storage="_FlagPub", DbType="VarChar(1)")]
	public System.Nullable<char> FlagPub
	{
		get
		{
			return this._FlagPub;
		}
		set
		{
			if ((this._FlagPub != value))
			{
				this._FlagPub = value;
			}
		}
	}
}
#pragma warning restore 1591
