#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V2")]
public partial class linQ_rsk_tables : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_cad_risk_fMitigador(tbl_cad_risk_fMitigador instance);
  partial void Updatetbl_cad_risk_fMitigador(tbl_cad_risk_fMitigador instance);
  partial void Deletetbl_cad_risk_fMitigador(tbl_cad_risk_fMitigador instance);
  partial void Inserttbl_cad_risk_qualiRisco(tbl_cad_risk_qualiRisco instance);
  partial void Updatetbl_cad_risk_qualiRisco(tbl_cad_risk_qualiRisco instance);
  partial void Deletetbl_cad_risk_qualiRisco(tbl_cad_risk_qualiRisco instance);
  partial void Inserttbl_riskManager_Detalhe(tbl_riskManager_Detalhe instance);
  partial void Updatetbl_riskManager_Detalhe(tbl_riskManager_Detalhe instance);
  partial void Deletetbl_riskManager_Detalhe(tbl_riskManager_Detalhe instance);
  partial void Inserttbl_riskManager(tbl_riskManager instance);
  partial void Updatetbl_riskManager(tbl_riskManager instance);
  partial void Deletetbl_riskManager(tbl_riskManager instance);
  #endregion
	
	public linQ_rsk_tables() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_tables(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_tables(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_tables(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linQ_rsk_tables(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_cad_risk_fMitigador> tbl_cad_risk_fMitigadors
	{
		get
		{
			return this.GetTable<tbl_cad_risk_fMitigador>();
		}
	}
	
	public System.Data.Linq.Table<tbl_cad_risk_qualiRisco> tbl_cad_risk_qualiRiscos
	{
		get
		{
			return this.GetTable<tbl_cad_risk_qualiRisco>();
		}
	}
	
	public System.Data.Linq.Table<tbl_riskManager_Detalhe> tbl_riskManager_Detalhes
	{
		get
		{
			return this.GetTable<tbl_riskManager_Detalhe>();
		}
	}
	
	public System.Data.Linq.Table<tbl_riskManager> tbl_riskManagers
	{
		get
		{
			return this.GetTable<tbl_riskManager>();
		}
	}
	
	public System.Data.Linq.Table<tbl_riskManager_detalhes_ft_Mitigador> tbl_riskManager_detalhes_ft_Mitigadors
	{
		get
		{
			return this.GetTable<tbl_riskManager_detalhes_ft_Mitigador>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cad_risk_fMitigador")]
public partial class tbl_cad_risk_fMitigador : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _DescFatorMit;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDescFatorMitChanging(string value);
    partial void OnDescFatorMitChanged();
    #endregion
	
	public tbl_cad_risk_fMitigador()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFatorMit", DbType="VarChar(150)")]
	public string DescFatorMit
	{
		get
		{
			return this._DescFatorMit;
		}
		set
		{
			if ((this._DescFatorMit != value))
			{
				this.OnDescFatorMitChanging(value);
				this.SendPropertyChanging();
				this._DescFatorMit = value;
				this.SendPropertyChanged("DescFatorMit");
				this.OnDescFatorMitChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cad_risk_qualiRiscos")]
public partial class tbl_cad_risk_qualiRisco : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _DescRisco;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDescRiscoChanging(string value);
    partial void OnDescRiscoChanged();
    #endregion
	
	public tbl_cad_risk_qualiRisco()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescRisco", DbType="VarChar(350)")]
	public string DescRisco
	{
		get
		{
			return this._DescRisco;
		}
		set
		{
			if ((this._DescRisco != value))
			{
				this.OnDescRiscoChanging(value);
				this.SendPropertyChanging();
				this._DescRisco = value;
				this.SendPropertyChanged("DescRisco");
				this.OnDescRiscoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_riskManager_Detalhes")]
public partial class tbl_riskManager_Detalhe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _RiskID;
	
	private string _Qualificacao;
	
	private string _Desc;
	
	private string _ItemContrato;
	
	private System.Nullable<decimal> _ValorImpactoRisco;
	
	private string _OcorrenciaX;
	
	private string _ImpactoY;
	
	private string _DescFatorM;
	
	private System.Nullable<decimal> _ValorFatorM;
	
	private System.Nullable<decimal> _ValorImpactoReal;
	
	private System.Nullable<int> _GrauRisco;
	
	private System.Nullable<int> _impactoXmetrica;
	
	private EntityRef<tbl_riskManager> _tbl_riskManager;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnRiskIDChanging(System.Nullable<int> value);
    partial void OnRiskIDChanged();
    partial void OnQualificacaoChanging(string value);
    partial void OnQualificacaoChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    partial void OnItemContratoChanging(string value);
    partial void OnItemContratoChanged();
    partial void OnValorImpactoRiscoChanging(System.Nullable<decimal> value);
    partial void OnValorImpactoRiscoChanged();
    partial void OnOcorrenciaXChanging(string value);
    partial void OnOcorrenciaXChanged();
    partial void OnImpactoYChanging(string value);
    partial void OnImpactoYChanged();
    partial void OnDescFatorMChanging(string value);
    partial void OnDescFatorMChanged();
    partial void OnValorFatorMChanging(System.Nullable<decimal> value);
    partial void OnValorFatorMChanged();
    partial void OnValorImpactoRealChanging(System.Nullable<decimal> value);
    partial void OnValorImpactoRealChanged();
    partial void OnGrauRiscoChanging(System.Nullable<int> value);
    partial void OnGrauRiscoChanged();
    partial void OnimpactoXmetricaChanging(System.Nullable<int> value);
    partial void OnimpactoXmetricaChanged();
    #endregion
	
	public tbl_riskManager_Detalhe()
	{
		this._tbl_riskManager = default(EntityRef<tbl_riskManager>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RiskID", DbType="Int")]
	public System.Nullable<int> RiskID
	{
		get
		{
			return this._RiskID;
		}
		set
		{
			if ((this._RiskID != value))
			{
				if (this._tbl_riskManager.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnRiskIDChanging(value);
				this.SendPropertyChanging();
				this._RiskID = value;
				this.SendPropertyChanged("RiskID");
				this.OnRiskIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualificacao", DbType="VarChar(150)")]
	public string Qualificacao
	{
		get
		{
			return this._Qualificacao;
		}
		set
		{
			if ((this._Qualificacao != value))
			{
				this.OnQualificacaoChanging(value);
				this.SendPropertyChanging();
				this._Qualificacao = value;
				this.SendPropertyChanged("Qualificacao");
				this.OnQualificacaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="VarChar(200)")]
	public string Desc
	{
		get
		{
			return this._Desc;
		}
		set
		{
			if ((this._Desc != value))
			{
				this.OnDescChanging(value);
				this.SendPropertyChanging();
				this._Desc = value;
				this.SendPropertyChanged("Desc");
				this.OnDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemContrato", DbType="VarChar(200)")]
	public string ItemContrato
	{
		get
		{
			return this._ItemContrato;
		}
		set
		{
			if ((this._ItemContrato != value))
			{
				this.OnItemContratoChanging(value);
				this.SendPropertyChanging();
				this._ItemContrato = value;
				this.SendPropertyChanged("ItemContrato");
				this.OnItemContratoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorImpactoRisco", DbType="Money")]
	public System.Nullable<decimal> ValorImpactoRisco
	{
		get
		{
			return this._ValorImpactoRisco;
		}
		set
		{
			if ((this._ValorImpactoRisco != value))
			{
				this.OnValorImpactoRiscoChanging(value);
				this.SendPropertyChanging();
				this._ValorImpactoRisco = value;
				this.SendPropertyChanged("ValorImpactoRisco");
				this.OnValorImpactoRiscoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OcorrenciaX", DbType="VarChar(50)")]
	public string OcorrenciaX
	{
		get
		{
			return this._OcorrenciaX;
		}
		set
		{
			if ((this._OcorrenciaX != value))
			{
				this.OnOcorrenciaXChanging(value);
				this.SendPropertyChanging();
				this._OcorrenciaX = value;
				this.SendPropertyChanged("OcorrenciaX");
				this.OnOcorrenciaXChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpactoY", DbType="VarChar(50)")]
	public string ImpactoY
	{
		get
		{
			return this._ImpactoY;
		}
		set
		{
			if ((this._ImpactoY != value))
			{
				this.OnImpactoYChanging(value);
				this.SendPropertyChanging();
				this._ImpactoY = value;
				this.SendPropertyChanged("ImpactoY");
				this.OnImpactoYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFatorM", DbType="VarChar(50)")]
	public string DescFatorM
	{
		get
		{
			return this._DescFatorM;
		}
		set
		{
			if ((this._DescFatorM != value))
			{
				this.OnDescFatorMChanging(value);
				this.SendPropertyChanging();
				this._DescFatorM = value;
				this.SendPropertyChanged("DescFatorM");
				this.OnDescFatorMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorFatorM", DbType="Money")]
	public System.Nullable<decimal> ValorFatorM
	{
		get
		{
			return this._ValorFatorM;
		}
		set
		{
			if ((this._ValorFatorM != value))
			{
				this.OnValorFatorMChanging(value);
				this.SendPropertyChanging();
				this._ValorFatorM = value;
				this.SendPropertyChanged("ValorFatorM");
				this.OnValorFatorMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorImpactoReal", DbType="Money")]
	public System.Nullable<decimal> ValorImpactoReal
	{
		get
		{
			return this._ValorImpactoReal;
		}
		set
		{
			if ((this._ValorImpactoReal != value))
			{
				this.OnValorImpactoRealChanging(value);
				this.SendPropertyChanging();
				this._ValorImpactoReal = value;
				this.SendPropertyChanged("ValorImpactoReal");
				this.OnValorImpactoRealChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrauRisco", DbType="Int")]
	public System.Nullable<int> GrauRisco
	{
		get
		{
			return this._GrauRisco;
		}
		set
		{
			if ((this._GrauRisco != value))
			{
				this.OnGrauRiscoChanging(value);
				this.SendPropertyChanging();
				this._GrauRisco = value;
				this.SendPropertyChanged("GrauRisco");
				this.OnGrauRiscoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impactoXmetrica", DbType="Int")]
	public System.Nullable<int> impactoXmetrica
	{
		get
		{
			return this._impactoXmetrica;
		}
		set
		{
			if ((this._impactoXmetrica != value))
			{
				this.OnimpactoXmetricaChanging(value);
				this.SendPropertyChanging();
				this._impactoXmetrica = value;
				this.SendPropertyChanged("impactoXmetrica");
				this.OnimpactoXmetricaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_riskManager_tbl_riskManager_Detalhe", Storage="_tbl_riskManager", ThisKey="RiskID", OtherKey="ID", IsForeignKey=true)]
	public tbl_riskManager tbl_riskManager
	{
		get
		{
			return this._tbl_riskManager.Entity;
		}
		set
		{
			tbl_riskManager previousValue = this._tbl_riskManager.Entity;
			if (((previousValue != value) 
						|| (this._tbl_riskManager.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_riskManager.Entity = null;
					previousValue.tbl_riskManager_Detalhes.Remove(this);
				}
				this._tbl_riskManager.Entity = value;
				if ((value != null))
				{
					value.tbl_riskManager_Detalhes.Add(this);
					this._RiskID = value.ID;
				}
				else
				{
					this._RiskID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_riskManager");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_riskManager")]
public partial class tbl_riskManager : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TipoVenda;
	
	private System.Nullable<int> _ContratoID;
	
	private string _DescCN;
	
	private string _SitContratual;
	
	private string _RiscoInadimplencia;
	
	private string _CasoGreveComau;
	
	private string _CasoForcaMaior;
	
	private string _DataVigencia;
	
	private string _RefEconomico;
	
	private string _BaseFat;
	
	private System.Nullable<decimal> _BaseFatValor;
	
	private System.Nullable<double> _MT_Baixa;
	
	private System.Nullable<double> _MT_Alta;
	
	private EntitySet<tbl_riskManager_Detalhe> _tbl_riskManager_Detalhes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTipoVendaChanging(string value);
    partial void OnTipoVendaChanged();
    partial void OnContratoIDChanging(System.Nullable<int> value);
    partial void OnContratoIDChanged();
    partial void OnDescCNChanging(string value);
    partial void OnDescCNChanged();
    partial void OnSitContratualChanging(string value);
    partial void OnSitContratualChanged();
    partial void OnRiscoInadimplenciaChanging(string value);
    partial void OnRiscoInadimplenciaChanged();
    partial void OnCasoGreveComauChanging(string value);
    partial void OnCasoGreveComauChanged();
    partial void OnCasoForcaMaiorChanging(string value);
    partial void OnCasoForcaMaiorChanged();
    partial void OnDataVigenciaChanging(string value);
    partial void OnDataVigenciaChanged();
    partial void OnRefEconomicoChanging(string value);
    partial void OnRefEconomicoChanged();
    partial void OnBaseFatChanging(string value);
    partial void OnBaseFatChanged();
    partial void OnBaseFatValorChanging(System.Nullable<decimal> value);
    partial void OnBaseFatValorChanged();
    partial void OnMT_BaixaChanging(System.Nullable<double> value);
    partial void OnMT_BaixaChanged();
    partial void OnMT_AltaChanging(System.Nullable<double> value);
    partial void OnMT_AltaChanged();
    #endregion
	
	public tbl_riskManager()
	{
		this._tbl_riskManager_Detalhes = new EntitySet<tbl_riskManager_Detalhe>(new Action<tbl_riskManager_Detalhe>(this.attach_tbl_riskManager_Detalhes), new Action<tbl_riskManager_Detalhe>(this.detach_tbl_riskManager_Detalhes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVenda", DbType="VarChar(50)")]
	public string TipoVenda
	{
		get
		{
			return this._TipoVenda;
		}
		set
		{
			if ((this._TipoVenda != value))
			{
				this.OnTipoVendaChanging(value);
				this.SendPropertyChanging();
				this._TipoVenda = value;
				this.SendPropertyChanged("TipoVenda");
				this.OnTipoVendaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContratoID", DbType="Int")]
	public System.Nullable<int> ContratoID
	{
		get
		{
			return this._ContratoID;
		}
		set
		{
			if ((this._ContratoID != value))
			{
				this.OnContratoIDChanging(value);
				this.SendPropertyChanging();
				this._ContratoID = value;
				this.SendPropertyChanged("ContratoID");
				this.OnContratoIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescCN", DbType="VarChar(250)")]
	public string DescCN
	{
		get
		{
			return this._DescCN;
		}
		set
		{
			if ((this._DescCN != value))
			{
				this.OnDescCNChanging(value);
				this.SendPropertyChanging();
				this._DescCN = value;
				this.SendPropertyChanged("DescCN");
				this.OnDescCNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SitContratual", DbType="VarChar(50)")]
	public string SitContratual
	{
		get
		{
			return this._SitContratual;
		}
		set
		{
			if ((this._SitContratual != value))
			{
				this.OnSitContratualChanging(value);
				this.SendPropertyChanging();
				this._SitContratual = value;
				this.SendPropertyChanged("SitContratual");
				this.OnSitContratualChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RiscoInadimplencia", DbType="VarChar(50)")]
	public string RiscoInadimplencia
	{
		get
		{
			return this._RiscoInadimplencia;
		}
		set
		{
			if ((this._RiscoInadimplencia != value))
			{
				this.OnRiscoInadimplenciaChanging(value);
				this.SendPropertyChanging();
				this._RiscoInadimplencia = value;
				this.SendPropertyChanged("RiscoInadimplencia");
				this.OnRiscoInadimplenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasoGreveComau", DbType="VarChar(50)")]
	public string CasoGreveComau
	{
		get
		{
			return this._CasoGreveComau;
		}
		set
		{
			if ((this._CasoGreveComau != value))
			{
				this.OnCasoGreveComauChanging(value);
				this.SendPropertyChanging();
				this._CasoGreveComau = value;
				this.SendPropertyChanged("CasoGreveComau");
				this.OnCasoGreveComauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasoForcaMaior", DbType="VarChar(50)")]
	public string CasoForcaMaior
	{
		get
		{
			return this._CasoForcaMaior;
		}
		set
		{
			if ((this._CasoForcaMaior != value))
			{
				this.OnCasoForcaMaiorChanging(value);
				this.SendPropertyChanging();
				this._CasoForcaMaior = value;
				this.SendPropertyChanged("CasoForcaMaior");
				this.OnCasoForcaMaiorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVigencia", DbType="VarChar(10)")]
	public string DataVigencia
	{
		get
		{
			return this._DataVigencia;
		}
		set
		{
			if ((this._DataVigencia != value))
			{
				this.OnDataVigenciaChanging(value);
				this.SendPropertyChanging();
				this._DataVigencia = value;
				this.SendPropertyChanged("DataVigencia");
				this.OnDataVigenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefEconomico", DbType="VarChar(50)")]
	public string RefEconomico
	{
		get
		{
			return this._RefEconomico;
		}
		set
		{
			if ((this._RefEconomico != value))
			{
				this.OnRefEconomicoChanging(value);
				this.SendPropertyChanging();
				this._RefEconomico = value;
				this.SendPropertyChanged("RefEconomico");
				this.OnRefEconomicoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseFat", DbType="VarChar(50)")]
	public string BaseFat
	{
		get
		{
			return this._BaseFat;
		}
		set
		{
			if ((this._BaseFat != value))
			{
				this.OnBaseFatChanging(value);
				this.SendPropertyChanging();
				this._BaseFat = value;
				this.SendPropertyChanged("BaseFat");
				this.OnBaseFatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseFatValor", DbType="Money")]
	public System.Nullable<decimal> BaseFatValor
	{
		get
		{
			return this._BaseFatValor;
		}
		set
		{
			if ((this._BaseFatValor != value))
			{
				this.OnBaseFatValorChanging(value);
				this.SendPropertyChanging();
				this._BaseFatValor = value;
				this.SendPropertyChanged("BaseFatValor");
				this.OnBaseFatValorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MT_Baixa", DbType="Float")]
	public System.Nullable<double> MT_Baixa
	{
		get
		{
			return this._MT_Baixa;
		}
		set
		{
			if ((this._MT_Baixa != value))
			{
				this.OnMT_BaixaChanging(value);
				this.SendPropertyChanging();
				this._MT_Baixa = value;
				this.SendPropertyChanged("MT_Baixa");
				this.OnMT_BaixaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MT_Alta", DbType="Float")]
	public System.Nullable<double> MT_Alta
	{
		get
		{
			return this._MT_Alta;
		}
		set
		{
			if ((this._MT_Alta != value))
			{
				this.OnMT_AltaChanging(value);
				this.SendPropertyChanging();
				this._MT_Alta = value;
				this.SendPropertyChanged("MT_Alta");
				this.OnMT_AltaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_riskManager_tbl_riskManager_Detalhe", Storage="_tbl_riskManager_Detalhes", ThisKey="ID", OtherKey="RiskID")]
	public EntitySet<tbl_riskManager_Detalhe> tbl_riskManager_Detalhes
	{
		get
		{
			return this._tbl_riskManager_Detalhes;
		}
		set
		{
			this._tbl_riskManager_Detalhes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_riskManager_Detalhes(tbl_riskManager_Detalhe entity)
	{
		this.SendPropertyChanging();
		entity.tbl_riskManager = this;
	}
	
	private void detach_tbl_riskManager_Detalhes(tbl_riskManager_Detalhe entity)
	{
		this.SendPropertyChanging();
		entity.tbl_riskManager = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_riskManager_detalhes_ft_Mitigador")]
public partial class tbl_riskManager_detalhes_ft_Mitigador
{
	
	private int _id;
	
	private System.Nullable<int> _DetID;
	
	private string _DescFatorM;
	
	private System.Nullable<decimal> _ValorFatorM;
	
	public tbl_riskManager_detalhes_ft_Mitigador()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetID", DbType="Int")]
	public System.Nullable<int> DetID
	{
		get
		{
			return this._DetID;
		}
		set
		{
			if ((this._DetID != value))
			{
				this._DetID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFatorM", DbType="VarChar(50)")]
	public string DescFatorM
	{
		get
		{
			return this._DescFatorM;
		}
		set
		{
			if ((this._DescFatorM != value))
			{
				this._DescFatorM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorFatorM", DbType="Money")]
	public System.Nullable<decimal> ValorFatorM
	{
		get
		{
			return this._ValorFatorM;
		}
		set
		{
			if ((this._ValorFatorM != value))
			{
				this._ValorFatorM = value;
			}
		}
	}
}
#pragma warning restore 1591
