#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGC_NET_V1")]
public partial class _linQ_ActualDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public _linQ_ActualDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGC_NET_V1ConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ActualDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ActualDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ActualDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public _linQ_ActualDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FxForecast_Acum", IsComposable=true)]
	public System.Nullable<double> FxForecast_Acum([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContaID", DbType="Int")] System.Nullable<int> contaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Perc", DbType="Int")] System.Nullable<int> perc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BU", DbType="VarChar(50)")] string bU)
	{
		return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contaID, ano, contratoID, perc, bU).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FxForecast_br_Acum", IsComposable=true)]
	public System.Nullable<double> FxForecast_br_Acum([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContaID", DbType="Int")] System.Nullable<int> contaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Perc", DbType="Int")] System.Nullable<int> perc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BU", DbType="VarChar(50)")] string bU)
	{
		return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contaID, ano, perc, bU).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FxRAG_Acum", IsComposable=true)]
	public System.Nullable<double> FxRAG_Acum([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContaID", DbType="Int")] System.Nullable<int> contaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="Int")] System.Nullable<int> ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContratoID", DbType="Int")] System.Nullable<int> contratoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Perc", DbType="Int")] System.Nullable<int> perc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BU", DbType="VarChar(50)")] string bU)
	{
		return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contaID, ano, contratoID, perc, bU).ReturnValue));
	}
}
#pragma warning restore 1591
